# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/pluto/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/zte/pluto/proprietary/bin/akmd8962:system/bin/akmd8962 \
    vendor/zte/pluto/proprietary/bin/atcmdsrv:system/bin/atcmdsrv \
    vendor/zte/pluto/proprietary/bin/btmacwriter:system/bin/btmacwriter \
    vendor/zte/pluto/proprietary/bin/cluster:system/bin/cluster \
    vendor/zte/pluto/proprietary/bin/cluster_get.sh:system/bin/cluster_get.sh \
    vendor/zte/pluto/proprietary/bin/cluster_set.sh:system/bin/cluster_set.sh \
    vendor/zte/pluto/proprietary/bin/dcc:system/bin/dcc \
    vendor/zte/pluto/proprietary/bin/gsmmuxd:system/bin/gsmmuxd \
    vendor/zte/pluto/proprietary/bin/hotplug:system/bin/hotplug \
    vendor/zte/pluto/proprietary/bin/input_cfboost_init.sh:system/bin/input_cfboost_init.sh \
    vendor/zte/pluto/proprietary/bin/mount_debugfs.sh:system/bin/mount_debugfs.sh \
    vendor/zte/pluto/proprietary/bin/nvcap_test:system/bin/nvcap_test \
    vendor/zte/pluto/proprietary/bin/nvcpud:system/bin/nvcpud \
    vendor/zte/pluto/proprietary/bin/nv_hciattach:system/bin/nv_hciattach \
    vendor/zte/pluto/proprietary/bin/nvtest:system/bin/nvtest \
    vendor/zte/pluto/proprietary/bin/powerservice:system/bin/powerservice \
    vendor/zte/pluto/proprietary/bin/rild:system/bin/rild \
    vendor/zte/pluto/proprietary/bin/rm_ts_server:system/bin/rm_ts_server \
    vendor/zte/pluto/proprietary/bin/set_hwui_params.sh:system/bin/set_hwui_params.sh \
    vendor/zte/pluto/proprietary/bin/tegrastats:system/bin/tegrastats \
    vendor/zte/pluto/proprietary/bin/wifi_loader.sh:system/bin/wifi_loader.sh \
    vendor/zte/pluto/proprietary/etc/acc_led:system/etc/acc_led \
    vendor/zte/pluto/proprietary/etc/acc_ptr:system/etc/acc_ptr \
    vendor/zte/pluto/proprietary/etc/bluetooth/bdaddr:system/etc/bluetooth/bdaddr \
    vendor/zte/pluto/proprietary/etc/buttons:system/etc/buttons \
    vendor/zte/pluto/proprietary/etc/firmware/bcm43241.hcd:system/etc/firmware/bcm43241.hcd \
    vendor/zte/pluto/proprietary/etc/firmware/bcm4329.hcd:system/etc/firmware/bcm4329.hcd \
    vendor/zte/pluto/proprietary/etc/firmware/bcm4330.hcd:system/etc/firmware/bcm4330.hcd \
    vendor/zte/pluto/proprietary/etc/firmware/bcm43341a0.hcd:system/etc/firmware/bcm43341a0.hcd \
    vendor/zte/pluto/proprietary/etc/firmware/bcm43341b0.hcd:system/etc/firmware/bcm43341b0.hcd \
    vendor/zte/pluto/proprietary/etc/firmware/js_it.bin:system/etc/firmware/js_it.bin \
    vendor/zte/pluto/proprietary/etc/firmware/LC1710_TDP_TOSHIBA.axf:system/etc/firmware/LC1710_TDP_TOSHIBA.axf \
    vendor/zte/pluto/proprietary/etc/firmware/LC1710_TL_UART.axf:system/etc/firmware/LC1710_TL_UART.axf \
    vendor/zte/pluto/proprietary/etc/firmware/LC1711MSA.bin:system/etc/firmware/LC1711MSA.bin \
    vendor/zte/pluto/proprietary/etc/firmware/maxim/00-RCV2.f095:system/etc/firmware/maxim/00-RCV2.f095 \
    vendor/zte/pluto/proprietary/etc/firmware/maxim/01-RCV1.f095:system/etc/firmware/maxim/01-RCV1.f095 \
    vendor/zte/pluto/proprietary/etc/firmware/maxim/02-SPK.f095:system/etc/firmware/maxim/02-SPK.f095 \
    vendor/zte/pluto/proprietary/etc/firmware/maxim/03-WHS.f095:system/etc/firmware/maxim/03-WHS.f095 \
    vendor/zte/pluto/proprietary/etc/firmware/maxim/04-WHS_MIC.f095:system/etc/firmware/maxim/04-WHS_MIC.f095 \
    vendor/zte/pluto/proprietary/etc/firmware/nandbooter_B.bin:system/etc/firmware/nandbooter_B.bin \
    vendor/zte/pluto/proprietary/etc/firmware/nand_system.img:system/etc/firmware/nand_system.img \
    vendor/zte/pluto/proprietary/etc/firmware/nvavp_aud_ucode.bin:system/etc/firmware/nvavp_aud_ucode.bin \
    vendor/zte/pluto/proprietary/etc/firmware/nvavp_os_0ff00000.bin:system/etc/firmware/nvavp_os_0ff00000.bin \
    vendor/zte/pluto/proprietary/etc/firmware/nvavp_os_eff00000.bin:system/etc/firmware/nvavp_os_eff00000.bin \
    vendor/zte/pluto/proprietary/etc/firmware/nvavp_vid_ucode_alt.bin:system/etc/firmware/nvavp_vid_ucode_alt.bin \
    vendor/zte/pluto/proprietary/etc/firmware/tegra11x/nvhost_msenc02.fw:system/etc/firmware/tegra11x/nvhost_msenc02.fw \
    vendor/zte/pluto/proprietary/etc/firmware/tegra11x/nvhost_tsec.fw:system/etc/firmware/tegra11x/nvhost_tsec.fw \
    vendor/zte/pluto/proprietary/etc/ir_ptr:system/etc/ir_ptr \
    vendor/zte/pluto/proprietary/etc/nunchuk_acc_ptr:system/etc/nunchuk_acc_ptr \
    vendor/zte/pluto/proprietary/etc/nunchuk_stick2btn:system/etc/nunchuk_stick2btn \
    vendor/zte/pluto/proprietary/etc/nvram_43341.txt:system/etc/nvram_43341.txt \
    vendor/zte/pluto/proprietary/etc/ppp/ip-up-vpn:system/etc/ppp/ip-up-vpn \
    vendor/zte/pluto/proprietary/lib/egl/libEGL_tegra_impl.so:system/lib/egl/libEGL_tegra_impl.so \
    vendor/zte/pluto/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/zte/pluto/proprietary/lib/egl/libGLESv1_CM_tegra_impl.so:system/lib/egl/libGLESv1_CM_tegra_impl.so \
    vendor/zte/pluto/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/zte/pluto/proprietary/lib/egl/libGLESv2_tegra_impl.so:system/lib/egl/libGLESv2_tegra_impl.so \
    vendor/zte/pluto/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
    vendor/zte/pluto/proprietary/lib/hw/audio.primary.tegra.so:system/lib/hw/audio.primary.tegra.so \
    vendor/zte/pluto/proprietary/lib/hw/camera.tegra.so:system/lib/hw/camera.tegra.so \
    vendor/zte/pluto/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/zte/pluto/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/zte/pluto/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
    vendor/zte/pluto/proprietary/lib/hw/lights.tegra_pluto.so:system/lib/hw/lights.tegra_pluto.so \
    vendor/zte/pluto/proprietary/lib/hw/nfc_nci.tegra_pluto.so:system/lib/hw/nfc_nci.tegra_pluto.so \
    vendor/zte/pluto/proprietary/lib/hw/nfc.tegra.so:system/lib/hw/nfc.tegra.so \
    vendor/zte/pluto/proprietary/lib/hw/sensors.tegra_pluto.so:system/lib/hw/sensors.tegra_pluto.so \
    vendor/zte/pluto/proprietary/lib/hw/ts.default.so:system/lib/hw/ts.default.so \
    vendor/zte/pluto/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
    vendor/zte/pluto/proprietary/lib/libaudioavp.so:system/lib/libaudioavp.so \
    vendor/zte/pluto/proprietary/lib/libbt-client-api.so:system/lib/libbt-client-api.so \
    vendor/zte/pluto/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
    vendor/zte/pluto/proprietary/lib/libcplconnectclient.so:system/lib/libcplconnectclient.so \
    vendor/zte/pluto/proprietary/lib/libinvensense_hal.so:system/lib/libinvensense_hal.so \
    vendor/zte/pluto/proprietary/lib/libjni_nvremoteprotopkg.so:system/lib/libjni_nvremoteprotopkg.so \
    vendor/zte/pluto/proprietary/lib/libjni_nvremote.so:system/lib/libjni_nvremote.so \
    vendor/zte/pluto/proprietary/lib/libmllite.so:system/lib/libmllite.so \
    vendor/zte/pluto/proprietary/lib/libmplmpu.so:system/lib/libmplmpu.so \
    vendor/zte/pluto/proprietary/lib/libnvapputil.so:system/lib/libnvapputil.so \
    vendor/zte/pluto/proprietary/lib/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
    vendor/zte/pluto/proprietary/lib/libnvaudioservice.so:system/lib/libnvaudioservice.so \
    vendor/zte/pluto/proprietary/lib/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
    vendor/zte/pluto/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
    vendor/zte/pluto/proprietary/lib/libnvblit.so:system/lib/libnvblit.so \
    vendor/zte/pluto/proprietary/lib/libnvcamerahdr.so:system/lib/libnvcamerahdr.so \
    vendor/zte/pluto/proprietary/lib/libnvcam_imageencoder.so:system/lib/libnvcam_imageencoder.so \
    vendor/zte/pluto/proprietary/lib/libnvcapaudioservice.so:system/lib/libnvcapaudioservice.so \
    vendor/zte/pluto/proprietary/lib/libnvcapclk.so:system/lib/libnvcapclk.so \
    vendor/zte/pluto/proprietary/lib/libnvcap.so:system/lib/libnvcap.so \
    vendor/zte/pluto/proprietary/lib/libnvcap_video.so:system/lib/libnvcap_video.so \
    vendor/zte/pluto/proprietary/lib/libnvcms.so:system/lib/libnvcms.so \
    vendor/zte/pluto/proprietary/lib/libnvcontrol_jni.so:system/lib/libnvcontrol_jni.so \
    vendor/zte/pluto/proprietary/lib/libnvcpl.so:system/lib/libnvcpl.so \
    vendor/zte/pluto/proprietary/lib/libnvcpud_client.so:system/lib/libnvcpud_client.so \
    vendor/zte/pluto/proprietary/lib/libnvcpud.so:system/lib/libnvcpud.so \
    vendor/zte/pluto/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
    vendor/zte/pluto/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
    vendor/zte/pluto/proprietary/lib/libnvfusebypass.so:system/lib/libnvfusebypass.so \
    vendor/zte/pluto/proprietary/lib/libnvglsi.so:system/lib/libnvglsi.so \
    vendor/zte/pluto/proprietary/lib/libnvhdmi3dplay_jni.so:system/lib/libnvhdmi3dplay_jni.so \
    vendor/zte/pluto/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
    vendor/zte/pluto/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
    vendor/zte/pluto/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
    vendor/zte/pluto/proprietary/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
    vendor/zte/pluto/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
    vendor/zte/pluto/proprietary/lib/libnvmmlite_image.so:system/lib/libnvmmlite_image.so \
    vendor/zte/pluto/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
    vendor/zte/pluto/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
    vendor/zte/pluto/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
    vendor/zte/pluto/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
    vendor/zte/pluto/proprietary/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
    vendor/zte/pluto/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
    vendor/zte/pluto/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
    vendor/zte/pluto/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
    vendor/zte/pluto/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
    vendor/zte/pluto/proprietary/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
    vendor/zte/pluto/proprietary/lib/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
    vendor/zte/pluto/proprietary/lib/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
    vendor/zte/pluto/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
    vendor/zte/pluto/proprietary/lib/libnvodm_misc.so:system/lib/libnvodm_misc.so \
    vendor/zte/pluto/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
    vendor/zte/pluto/proprietary/lib/libnvoice.so:system/lib/libnvoice.so \
    vendor/zte/pluto/proprietary/lib/libnvomxadaptor.so:system/lib/libnvomxadaptor.so \
    vendor/zte/pluto/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
    vendor/zte/pluto/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
    vendor/zte/pluto/proprietary/lib/libnvopt_dvm.so:system/lib/libnvopt_dvm.so \
    vendor/zte/pluto/proprietary/lib/libnvos.so:system/lib/libnvos.so \
    vendor/zte/pluto/proprietary/lib/libnvparser.so:system/lib/libnvparser.so \
    vendor/zte/pluto/proprietary/lib/libnvremoteevtmgr.so:system/lib/libnvremoteevtmgr.so \
    vendor/zte/pluto/proprietary/lib/libnvremotell.so:system/lib/libnvremotell.so \
    vendor/zte/pluto/proprietary/lib/libnvremoteprotocol.so:system/lib/libnvremoteprotocol.so \
    vendor/zte/pluto/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
    vendor/zte/pluto/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
    vendor/zte/pluto/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
    vendor/zte/pluto/proprietary/lib/libnvstitching.so:system/lib/libnvstitching.so \
    vendor/zte/pluto/proprietary/lib/libnvtestio.so:system/lib/libnvtestio.so \
    vendor/zte/pluto/proprietary/lib/libnvtestresults.so:system/lib/libnvtestresults.so \
    vendor/zte/pluto/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
    vendor/zte/pluto/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
    vendor/zte/pluto/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
    vendor/zte/pluto/proprietary/lib/libopencv24_tegra.so:system/lib/libopencv24_tegra.so \
    vendor/zte/pluto/proprietary/lib/libpowerservice_client.so:system/lib/libpowerservice_client.so \
    vendor/zte/pluto/proprietary/lib/librm31080.so:system/lib/librm31080.so \
    vendor/zte/pluto/proprietary/lib/librm_ts_service.so:system/lib/librm_ts_service.so \
    vendor/zte/pluto/proprietary/lib/libsensors.base.so:system/lib/libsensors.base.so \
    vendor/zte/pluto/proprietary/lib/libsensors.isl29018.so:system/lib/libsensors.isl29018.so \
    vendor/zte/pluto/proprietary/lib/libsensors.isl29028.so:system/lib/libsensors.isl29028.so \
    vendor/zte/pluto/proprietary/lib/libsensors.mpl.so:system/lib/libsensors.mpl.so \
    vendor/zte/pluto/proprietary/lib/libsensors.nvs_input.so:system/lib/libsensors.nvs_input.so \
    vendor/zte/pluto/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/zte/pluto/proprietary/lib/libtbb.so:system/lib/libtbb.so \
    vendor/zte/pluto/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/zte/pluto/proprietary/lib/libtsechdcp.so:system/lib/libtsechdcp.so \
    vendor/zte/pluto/proprietary/lib/libtsec_wrapper.so:system/lib/libtsec_wrapper.so \
    vendor/zte/pluto/proprietary/lib/libzteflash.so:system/lib/libzteflash.so \
    vendor/zte/pluto/proprietary/lib/libztetd-ril.so:system/lib/libztetd-ril.so \
    vendor/zte/pluto/proprietary/lib/nvcms/device.cfg:system/lib/nvcms/device.cfg \
    vendor/zte/pluto/proprietary/vendor/lib/hw/power.tegra_pluto.so:system/vendor/lib/hw/power.tegra_pluto.so \
    vendor/zte/pluto/proprietary/xbin/BrcmNfcHwTest:system/xbin/BrcmNfcHwTest \
    vendor/zte/pluto/proprietary/xbin/gpstest:system/xbin/gpstest
